name = "jsonhero-io"
type = "javascript"
compatibility_date = "2022-02-01"

account_id = "********************************"
workers_dev = true

kv_namespaces = [ 
  { binding = "DOCUMENTS", id = "********************************" }
]

[vars]
GRAPH_JSON_COLLECTION = "jsonhero-dev"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"

[env.production]
route = "jsonhero.io/*"
zone_id = "********************************"
kv_namespaces = [ 
  { binding = "DOCUMENTS", id = "********************************" }
]

[env.production.vars]
GRAPH_JSON_COLLECTION = "jsonhero-prod"

# Secrets
# [SESSION_STORAGE]
# [GRAPH_JSON_API_KEY]
# [PEEKALINK_API_KEY]
# [APIHERO_PROJECT_KEY]